id: PEBE400DE
initial_creation_type: input
source_metadata:
  Title: Sarvabuddhaviṣayāvatārajñānālokālaṁkāra nāma mahāyānasūtra
  Editor: Takayasu Kimura, Nobuo Otsuka, Hideaki Kimura, Hisao Takahashi
  Publisher: Institute for Comprehensive Studies of Buddhism, Taisho University
  Place of Publication: Japan, Tokyo
  Year: '2004'
  सर्वबुद्धविषयावतारज्ञानालोकालंकार:
    Text Version: Devanagari
    Input Personnel: Miroj Shakya
    Input Date: '2020'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:24:48.794713'
last_modified_at: '2022-03-08T17:24:48.794722'
